apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "relayers-service.labels" . | nindent 4 }}
spec:
  selector:
    app: {{ .Values.relayer.name }}
  ports:
    - port: 3000
      targetPort: {{ .Values.relayer.port }}