apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "relayers-service.labels" . | nindent 4 }}
spec:
  backendType: gcpSecretsManager
  projectId: {{ .Values.secret.projectID }}
  data:
  - key:  {{ .Values.secret.key }}
    name: {{ .Values.secret.config.name }}
