{{- $replicas := .Values.replicas | int -}}
{{- $values := .Values }}
{{- range $i,$e := until $replicas }}
---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: {{ $values.relayer.name }}{{ $i }}
  namespace: {{ $values.namespace }}
  labels:
  {{- include "relayers-service.labels" $ | nindent 4 }}

spec:
  backendType: gcpSecretsManager
  projectId: {{ $values.secret.projectID }}
  data:
  - key:  {{ $values.secret.key }}-{{ $i }}
    name: {{ $values.secret.config.name }}
{{- end}}