apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.name }}-encrypted-secrets{{ .Values.index }}
  namespace: {{ .Values.namespace }}
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: {{ .Values.name }}-gsm-store
    kind: SecretStore
  target:
    name: {{ .Values.name }}-encrypted-secrets{{ .Values.index }} # k8s secret 
    creationPolicy: Owner
  data:
    - secretKey: {{ .Values.secret_encrypted.config.name }}   
      remoteRef:
        key: {{ .Values.secret_encrypted.key }}-{{ .Values.index }}            
        version: latest
