apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.relayer.name }}-passphrase
  namespace: {{ .Values.namespace }}
spec:
  backendType: gcpSecretsManager
  projectId: {{ .Values.secret.projectID }}
  data:
  - key:  {{ .Values.secret.passphrase.key }}
    name: {{ .Values.secret.passphrase.name }}
    version: {{ .Values.secret.passphrase.version }}
    property: {{ .Values.secret.passphrase.name }}
---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.relayer.name }}-plain
  namespace: {{ .Values.namespace }}
  labels:
  {{- include "relayers-service.labels" $ | nindent 4 }}

spec:
  backendType: gcpSecretsManager
  projectId: {{ .Values.secret_plain.projectID }}
  data:
  - key:  {{ .Values.secret_plain.key }}
    name: {{ .Values.secret_plain.config.name }}
---