apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ .Values.name }}-gsm-store
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "relayers-service.labels" . | nindent 4 }}
spec:
  provider:
    gcpsm:
      projectID: {{ .Values.secret.projectID }}
      auth:
        workloadIdentity:
          serviceAccountRef:
            name: sa-{{ .Values.name }}
---

apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.name }}-plain-secrets
  namespace: {{ .Values.namespace }}
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: {{ .Values.name }}-gsm-store
    kind: SecretStore
  target:
    name: {{ .Values.name }}-plain-secrets # k8s secret 
    creationPolicy: Owner
  data:
    - secretKey: {{ .Values.secret_plain.config.name }}   
      remoteRef:
        key: {{ .Values.secret_plain.key }}               
        version: latest

---

apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.name }}-passphrase-secrets
  namespace: {{ .Values.namespace }}
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: {{ .Values.name }}-gsm-store
    kind: SecretStore
  target:
    name: {{ .Values.name }}-passphrase-secrets # k8s secret 
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: {{ .Values.secret.passphrase.key }}
        version: latest