apiVersion: v1
kind: Pod
metadata:
  name: test-gcp-access
  namespace: trustwallet
spec:
  serviceAccountName: trustwal-trustwalle-prod-sa
  containers:
  - name: test-container
    image: google/cloud-sdk:latest
    command: ["/bin/sleep", "3600"]