version: "3.1"

volumes:
  redis-data:
  mongo-data:
  rabbitmq_log:
  rabbitmq_data:

services:
  server:
    container_name: api-service
    env_file: .env
    ports:
      - "0.0.0.0:3000:3000"
    depends_on:
      mongo:
        condition: service_started
      redis:
        condition: service_healthy
        restart: true
      rabbitmq:
        condition: service_healthy
        restart: true
      # centrifugo:
      #   condition: service_healthy
      #   restart: true
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    volumes:
      - .:/home/nonroot/bundler

  redis:
    image: redis:6.0
    container_name: redis
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "0.0.0.0:6379:6379"
    volumes:
      - redis-data:/data
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 5s
      timeout: 20s
      retries: 5

  centrifugo:
    container_name: centrifugo
    image: centrifugo/centrifugo:v3.2.2
    volumes:
      - ./centrifugo_config.json:/centrifugo/config.json
    command: centrifugo -c config.json
    healthcheck:
      test: ["CMD", "sh", "-c", "wget -nv -O - http://localhost:8000"]
      interval: 3s
      timeout: 3s
      retries: 3

    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    ports:
      - "0.0.0.0:8000:8000"

  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    ports:
      - "0.0.0.0:27017:27017"
    volumes:
      - mongo-data:/data/db

  rabbitmq:
    image: heidiks/rabbitmq-delayed-message-exchange:3.8.3-management
    container_name: "rabbitmq"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 5s
      timeout: 20s
      retries: 5
    ports:
      - "0.0.0.0:5672:5672"
      - "0.0.0.0:15672:15672"
    volumes:
      - rabbitmq_log:/var/log/rabbitmq
      - rabbitmq_data:/var/lib/rabbitmq
