volumes:
  redis-data:
  mongo-data:
  rabbitmq_log:
  rabbitmq_data:

services:
  bundler:
    container_name: bundler
    env_file: .env
    ports:
      - "3000:3000"
    links:
      - redis
      - mongo
      - rabbitmq
    depends_on:
      mongo:
        condition: service_started
      redis:
        condition: service_healthy
        restart: true
      rabbitmq:
        condition: service_healthy
        restart: true
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    volumes:
      - ./src:/home/nonroot/bundler/src
      - ./config:/home/nonroot/bundler/config
      - ./nodemon.json:/home/nonroot/bundler/nodemon.json
      - ./config.json.enc:/home/nonroot/bundler/config.json.enc
      - ./.env:/home/nonroot/bundler/.env

  redis:
    image: redis:latest
    container_name: redis
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 5s
      timeout: 20s
      retries: 5

  mongo:
    # see: https://www.mongodb.com/docs/manual/tutorial/install-mongodb-community-with-docker/#about-this-task
    # image: mongo:4.4
    image: mongo:latest
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  rabbitmq:
    image: heidiks/rabbitmq-delayed-message-exchange:latest
    container_name: "rabbitmq"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 5s
      timeout: 20s
      retries: 5
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_log:/var/log/rabbitmq
      - rabbitmq_data:/var/lib/rabbitmq
