apiVersion: v1
kind: Service
metadata:
  name: {{ include "centrifugo.fullname" . }}
  namespace: {{ include "centrifugo.namespace" . }}
  labels:
    {{- include "centrifugo.labels" . | nindent 4 }}
    {{- with .Values.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: external
      protocol: TCP
      {{- if .Values.service.appProtocol }}
      appProtocol: {{ .Values.service.appProtocol }}
      {{- end }}
      name: external
      {{- if (and (eq .Values.service.type "NodePort") (not (empty .Values.service.nodePort))) }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
{{- if not .Values.service.useSeparateInternalService }}
    - port: {{ .Values.internalService.port }}
      targetPort: internal
      protocol: TCP
      {{- if .Values.internalService.appProtocol }}
      appProtocol: {{ .Values.internalService.appProtocol }}
      {{- end }}
      name: internal
      {{- if (and (eq .Values.internalService.type "NodePort") (not (empty .Values.internalService.nodePort))) }}
      nodePort: {{ .Values.internalService.nodePort }}
      {{- end }}
{{- end }}
{{- if not .Values.service.useSeparateGrpcService }}
    - port: {{ .Values.grpcService.port }}
      targetPort: grpc
      protocol: TCP
      {{- if .Values.grpcService.appProtocol }}
      appProtocol: {{ .Values.grpcService.appProtocol }}
      {{- end }}
      name: grpc
      {{- if (and (eq .Values.grpcService.type "NodePort") (not (empty .Values.grpcService.nodePort))) }}
      nodePort: {{ .Values.grpcService.nodePort }}
      {{- end }}
{{- end }}
{{- if not .Values.service.useSeparateUniGrpcService }}
    - port: {{ .Values.uniGrpcService.port }}
      targetPort: uni-grpc
      protocol: TCP
      {{- if .Values.uniGrpcService.appProtocol }}
      appProtocol: {{ .Values.uniGrpcService.appProtocol }}
      {{- end }}
      name: uni-grpc
      {{- if (and (eq .Values.uniGrpcService.type "NodePort") (not (empty .Values.uniGrpcService.nodePort))) }}
      nodePort: {{ .Values.uniGrpcService.nodePort }}
      {{- end }}
{{- end }}
  selector:
    {{- include "centrifugo.selectorLabels" . | nindent 4 }}
