{{- if .Values.service.useSeparateUniGrpcService -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "centrifugo.fullname" . }}-uni-grpc
  namespace: {{ include "centrifugo.namespace" . }}
  labels:
    {{- include "centrifugo.labels" . | nindent 4 }}
    {{- with .Values.uniGrpcService.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.uniGrpcService.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.uniGrpcService.type }}
  ports:
    - port: {{ .Values.uniGrpcService.port }}
      targetPort: uni-grpc
      protocol: TCP
      {{- if .Values.uniGrpcService.appProtocol }}
      appProtocol: {{ .Values.uniGrpcService.appProtocol }}
      {{- end }}
      name: uni-grpc
      {{- if (and (eq .Values.uniGrpcService.type "NodePort") (not (empty .Values.uniGrpcService.nodePort))) }}
      nodePort: {{ .Values.uniGrpcService.nodePort }}
      {{- end }}
  selector:
    {{- include "centrifugo.selectorLabels" . | nindent 4 }}
{{- end }}
