name: "relayer-server"

relayer:
  name: "relayer-server"
  port: "3000"
  
namespace: "sdk-staging"

secret:
  projectID: biconomy-staging

  passphrase:
    key: sdk-staging-relayer-node-service-passphrase
    name: CONFIG_PASSPHRASE
    version: latest

ingress:
  host: sdk-relayer.staging.biconomy.io
  override: consistent-hashing

# datadog configs
affinity_tolerations:
  enable: false
  
datadog:
  enable: false
