/* eslint-disable max-len */
import { Request, Response } from 'express';
import { STATUSES } from '../../../middleware';
import { logger } from '../../../../../common/log-config';
import { userOperationDao } from '../../../../../common/service-manager';

const log = logger(module);

/**
 * userOpHash the request hash
  entryPoint
  sender
  nonce
  paymaster the paymaster used for this userOp (or empty)
  actualGasCost - actual amount paid (by account or paymaster) for this UserOperation
  actualGasUsed - total gas used by this UserOperation (including preVerification, creation, validation and execution)
  success boolean - did this execution completed without revert
  reason in case of revert, this is the revert reason
  logs the logs generated by this UserOperation (not including logs of other UserOperations in the same bundle)
  receipt the TransactionReceipt object. Note that the returned TransactionReceipt is for the entire bundle, not only for this UserOperation.
 */
export const getUserOperationReceipt = async (req: Request, res: Response) => {
  try {
    const userOpHash = req.body.params[0];
    const { chainId } = req.params;

    const userOperationData = await userOperationDao.getUserOperationDataByUserOpHash(
      parseInt(chainId, 10),
      userOpHash,
    );

    if (!userOperationData) {
      return {
        jsonrpc: '2.0',
        id: 1,
        result: null,
      };
    }

    const {
      entryPoint,
      sender,
      nonce,
      success,
      paymaster,
      actualGasCost,
      actualGasUsed,
      logs,
      receipt,
      reason,
    } = userOperationData;

    const result = {
      userOpHash,
      entryPoint,
      sender,
      nonce,
      success,
      paymaster,
      actualGasCost,
      actualGasUsed,
      reason,
      logs,
      receipt,
    };

    return res.status(STATUSES.SUCCESS).json({
      jsonrpc: '2.0',
      id: 1,
      result,
    });
  } catch (error) {
    log.error(`Error in supportedEntryPoints handler ${JSON.stringify(error)}`);
    return res.status(STATUSES.INTERNAL_SERVER_ERROR).json({
      code: STATUSES.INTERNAL_SERVER_ERROR,
      error: `Internal Server Error: ${JSON.stringify(error)}`,
    });
  }
};
