

## Redis&reg; Authentication parameters
architecture: replication
master:
  persistence:
    storageClass: "premium-rwo"
  resources:
    ## Example:
    limits:
      cpu: 250m
      memory: 250Mi
    requests:
      cpu: 512m
      memory: 512Mi

replica:
  replicaCount: 2
  resources:
    ## Example:
    limits:
      cpu: 250m
      memory: 250Mi
    requests:
      cpu: 512m
      memory: 512Mi