datasources:
  datasources.yaml:
      apiVersion: 1
      datasources:
        - access: proxy
          name: Prometheus
          type: prometheus
          url: http://qabundler-test-monitoring-prometheus-server

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
    - name: 'default'
      orgId: 1
      folder: ''
      type: file
      disableDeletion: false
      editable: true
      options:
        path: /var/lib/grafana/dashboards/default