
#https://cloud.google.com/kubernetes-engine/docs/how-to/managed-certs?cloudshell=true

apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
{{ include "chart.certificate.metadata" . | nindent 2 }}
spec:
  domains:
{{ toYaml .Values.domains | indent 4 }}
