apiVersion: v1
kind: ConfigMap
metadata: {{ include "chart.staticconfigmap.metadata" . | nindent 2 }}
data:
  BUNDLER_CHAIN_ID: "{{ .Values.CHAIN_ID }}"
  DD_PROFILING_ENABLED: "false"
  DD_ENV: "bundler-tw-staging"
  DD_SERVICE: {{ .Values.datadog.service }}
  DD_VERSION: "1.0.3"
