apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  # name: sample-app
{{ include "chart.hpa.metadata" . | nindent 2 }}

spec:
  scaleTargetRef:
    # point the HPA at the sample application
    # you created above
    apiVersion: apps/v1
    kind: StatefulSet
    name: {{ include "chart.statefulset.name" .}}

  # autoscale between 1 and 10 replicas
  minReplicas:  {{.Values.hpa.minReplicas}}
  maxReplicas:  {{.Values.hpa.maxReplicas}}
  metrics:
  # use a "Pods" metric, which takes the average of the
  # given metric across all pods controlled by the autoscaling target
  - type: Pods
    pods:
      # use the metric that you used above: pods/http_requests
      metric:
        name: {{.Values.CHAIN_ID}}-http-requests
      # target 500 milli-requests per second,
      # which is 1 request every two seconds
      # http_requests_per_two_minute metric goes beyond 100, 
      # then you should set the averageValue for that metric 
      # to 100 (or 100000m, as 1 = 1000m).
      target:
        type: AverageValue
        averageValue: {{.Values.hpa.average_http_requests_hpa}}
        
  
  - type: Pods
    pods:
      metric:
        name: {{.Values.CHAIN_ID}}-cpu-usage
      target:
        type: AverageValue
        averageValue: {{.Values.hpa.average_cpu_hpa}} # Adjust the averageValue as per your requirements.