{{- if eq .Values.env "test" }}

apiVersion: v1
kind: Secret
metadata:
  {{ include "chart.secret.metadata" . | nindent 2 }}

type: Opaque
data:
  # Assuming you want to use a base64 encoded secret for local test
  {{ .Values.secret.passphrase.name }}: {{ .Values.secret.passphrase.value | b64enc | quote }}

{{- end }}