apiVersion: v1
kind: Service
metadata:
{{ include "chart.service.metadata" . | nindent 2 }}
spec:
  selector:
  {{ include "chart.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.port }}
      targetPort: {{ .Values.targetPort }}